### ISSUE TITLE
New if statement causes crash

### ISSUE THREAD

**Issue by LewisGaul** [kjav/tic-tac-tic-tac-toe-toe#5]
Line 35 of board.py in latest commit causes crash immediately when running the program. Why was this added?

**Comment by kjav** [comment]
Presumably this has been removed in the recent tidy-up?

**Comment by LewisGaul** [comment]
I was just wondering that... I'll have a look at what line 35 was back then!

**Comment by LewisGaul** [comment]
This is the line - missing brackets to call the function: https://github.com/kjav/tic-tac-tic-tac-toe-toe/blob/0ee370f45c0f2d3d0e97f1a4f3ef0838808ffe89/board.py#L35

Looks like it's been fixed since then.
